In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('data/veri-manipulasyonu/bozuk_data.csv')

In [7]:
df.columns

Index(['id', 'grup', 'kurs_kodu', 'baseline_anket_tarihi', 'cinsiyet',
       'dogum_yili', 'baseline_calisma_durumu_son_4hafta',
       'baseline_calisma_durumu_20_saat', 'baseline_sgk_kaydi',
       'baseline_calisma_saat_ort', 'baseline_calisma_aylik_gelir_ort',
       'takip_tamamlama', 'takip_anket_tarihi',
       'takip_calisma_durumu_son_4hafta', 'takip_calisma_durumu_20_saat',
       'takip_sgk_kaydi', 'takip_calisma_saat_ort',
       'takip_calisma_aylik_gelir_ort', 'kurs_yeni_yetenekler_ogretti',
       'kurs_mevcut_yeteneklerimi_sertifikaladi',
       'kurs_is_bulma_stratejileri_ogretti', 'kursu_kim_verdi',
       'sgk_ocak_2012', 'sgk_agu_2013', 'sgk_agu_2013_gelir',
       'kurs_tamamlama_durumu', 'kursa_katilim_gun_sayisi', 'CP_c12',
       'CP_c13'],
      dtype='object')

In [8]:
baseline_df = df.loc[:, ['id', 'grup', 'baseline_anket_tarihi', 'cinsiyet',
       'dogum_yili', 'baseline_calisma_durumu_son_4hafta',
       'baseline_calisma_durumu_20_saat', 'baseline_sgk_kaydi',
       'baseline_calisma_saat_ort', 'baseline_calisma_aylik_gelir_ort']]

In [10]:
takip_df = df.loc[:, ['id', 'takip_tamamlama', 'takip_anket_tarihi',
       'takip_calisma_durumu_son_4hafta', 'takip_calisma_durumu_20_saat',
       'takip_sgk_kaydi', 'takip_calisma_saat_ort', 'takip_calisma_aylik_gelir_ort']]

In [12]:
sgk_df = df.loc[:, ['id', 'sgk_ocak_2012', 'sgk_agu_2013', 'sgk_agu_2013_gelir']]

In [13]:
iskur_df = df.loc[:, ['id', 'kurs_tamamlama_durumu', 'kursa_katilim_gun_sayisi', 'CP_c12',
       'CP_c13']]

In [16]:
baseline_df.to_csv('data/veri-manipulasyonu/baseline.csv', index = False, encoding = 'utf-8')
takip_df.to_csv('data/veri-manipulasyonu/takip.csv', index = False, encoding = 'utf-8')
sgk_df.to_csv('data/veri-manipulasyonu/sgk.csv', index = False, encoding = 'utf-8')
iskur_df.to_csv('data/veri-manipulasyonu/iskur.csv', index = False, encoding = 'utf-8')

In [7]:
df[df.duplicated()]

,id,grup,kurs_kodu,baseline_anket_tarihi,cinsiyet,dogum_yili,baseline_calisma_durumu_son_4hafta,baseline_calisma_durumu_20_saat,baseline_sgk_kaydi,baseline_calisma_saat_ort,...,kurs_mevcut_yeteneklerimi_sertifikaladi,kurs_is_bulma_stratejileri_ogretti,kursu_kim_verdi,sgk_ocak_2012,sgk_agu_2013,sgk_agu_2013_gelir,kurs_tamamlama_durumu,kursa_katilim_gun_sayisi,CP_c12,CP_c13
88,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
93,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
225,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
277,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
290,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5020,64281030,1,64281,2010-11-01,Female,1990,No,NaN,No,48.0,...,NaN,NaN,NaN,0.0,0.0,0.0,No,NaN,NaN,NaN
5028,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
5078,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
5088,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
5128,66837006,2,66837,2010-12-03,Female,1974,No,NaN,Yes,70.0,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN